spring:
  jpa:
    database: MYSQL
    hibernate:
      ddl-auto: validate

  datasource:
    url: jdbc:mysql://127.0.0.1/phpmyadmin/db_structure.php?server=1&db=runoob_db
    username:
    password:
driver-class-name: com.mysql.jdbc.Driver